# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-30 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
