# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-10 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAndRegister', '0002_auto_20181005_0820'),
        ('MessageWall', '0002_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recipient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='recipientPost', to='LoginAndRegister.User'),
            preserve_default=False,
        ),
    ]
