# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-29 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login_app', '0002_auto_20180927_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
    ]
